accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import (RegisterView, ProfileEditView,
                    ProfileDetailView,)

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^register/$',RegisterView.as_view(), name='register'),
    url(r'^edit/(?P<pk>\d+)/$',ProfileEditView.as_view(), name='profile_edit'),
    url(r'^profile/(?P<pk>\d+)/$',ProfileDetailView.as_view(), name='profile'),
]

game/urls.py
from django.conf.urls import url, include
from .views import (CreateProduct, ProductDetailView,
                    ProductUpdateView, ProductDeleteView,
                    ProductListView,)

app_name = 'game'

urlpatterns = [
    url(r'^create/$', CreateProduct.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', ProductDetailView.as_view(), name='product'),
    url(r'^(?P<pk>\d+)/edit$', ProductUpdateView.as_view(), name='product_edit'),
    url(r'^(?P<pk>\d+)/delete$', ProductDeleteView.as_view(), name='product_delete'),
]

thaigametrade/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import HomePageView, GameRequestView
from game.views import ProductListView, GameListView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^product/', include('game.urls')),
    url(r'^gamerequest/$', GameRequestView.as_view(), name='gamerequest'),
    url(r'^game/$', GameListView.as_view(), name='gamelist'),
    url(r'^game/(?P<pk>\d+)/$', ProductListView.as_view(), name='game'),
    url(r'^accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse

User = get_user_model()
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    facebook = models.CharField(max_length=100)
    facebook_link = models.URLField(null=True)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('home')

def create_profile(sender, **kwargs):
    if kwargs['created']:
        profile = Profile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

game/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from accounts.models import Profile

# Create your models here.
class Game(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)

class Product(models.Model):
    game = models.ForeignKey(Game, related_name='products')
    price = models.PositiveIntegerField()
    seller = models.ForeignKey(Profile, related_name='products')

    def __str__(self):
        return str(self.game) + " " + str(self.price) + " " + str(self.seller)

    def get_absolute_url(self):
        return reverse("game:product",kwargs={'pk':self.pk})

news/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class News(models.Model):
    time = models.DateTimeField(auto_now=True)
    text = models.CharField(max_length=600)

    def __str__(self):
        return str(self.text[:20])

class GameRequest(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('home')

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

game/forms.py
from django.forms import ModelForm
from .models import Game, Product

class ProductForm(forms.ModelForm):
    class Meta:
        fields = ("game", "price")
        model = Product

accounts/views.py
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (CreateView, UpdateView,
                                  DetailView,)

from . import forms, models

# Create your views here.
class RegisterView(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("accounts:login")
    template_name = "registration/register.html"

class ProfileEditView(UpdateView):
    fields = ('facebook','facebook_link',)
    template_name = 'registration/profile_edit.html'
    model = models.Profile

class ProfileDetailView(DetailView):
    context_object_name = 'profile'
    template_name = 'registration/profile_detail.html'
    model = models.Profile

game/views.py
from django.shortcuts import render
from django.views.generic import (CreateView, DetailView,
                                  UpdateView, DeleteView,
                                  ListView)
from .models import Game, Product

# Create your views here.
class CreateProduct(CreateView):
    fields = ('game','price')
    model = Product
    template_name = 'game/productcreate.html'
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.seller = self.request.user.profile
        self.object.save()
        return super().form_valid(form)

class ProductDetailView(DetailView):
    context_object_name = 'product_detail'
    model = Product
    template_name = 'game/productdetail.html'

class ProductUpdateView(UpdateView):
    fields = ('price',)
    model = Product
    template_name = 'game/productedit.html'

class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'game/productdelete.html'
    success_url = '/'

class ProductListView(DetailView):
    model = Game
    template_name = 'game/productlist.html'

class GameListView(ListView):
    model = Game
    template_name = 'game/gamelist.html'

    def get_queryset(self):
        q = self.request.GET.get('q')
        if(q):
            object_list = self.model.objects.filter(name__icontains=q)
        else:
            object_list = self.model.objects.all()
            
        return object_list

news/views.py
from django.shortcuts import render

# Create your views here.

thaigametrade/views.py
from django.views.generic.base import TemplateView
from django.views.generic import CreateView
from accounts.models import Profile
from game.models import Game
from news.models import News, GameRequest

class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profiles'] = Profile.objects.all()[:5]
        context['games'] = Game.objects.all()[:5]
        context['news'] = News.objects.order_by('time')[:5]
        return context

class GameRequestView(CreateView):
    model = GameRequest
    fields = ('name',)
    template_name = 'gamerequest.html'

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Thaigametrade</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="{% url 'home' %}"><strong>Thaigametrade</strong></a>
        <form class="form-inline">
        {% if user.is_authenticated %}
          <a href="{% url 'accounts:profile' pk=user.profile.pk %}">
            <button class="btn btn-sm btn-outline-primary mr-sm-2" type="button">หน้าผู้ใช้</button>
          </a>
          <a href="{% url 'game:create' %}">
            <button class="btn btn-sm btn-outline-primary mr-sm-2" type="button">ขายเกม</button>
          </a>
          <a href="{% url 'accounts:logout' %}">
            <button class="btn btn-sm btn-outline-primary mr-sm-2" type="button">ลงชื่อออก</button>
          </a>
        {% else %}
          <a href="{% url 'accounts:login' %}">
            <button class="btn btn-sm btn-outline-primary mr-sm-2" type="button">ลงชื่อเข้าใช้</button>
          </a>
        {% endif %}
        </form>
    </nav>
    <p></p>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/game/gamelist.html
{% extends 'base.html' %}
{% block content %}
<form class="form-inline" method="GET">
  <input class="form-control" type="text" name="q" placeholder="ค้นหาชื่อเกม">
  <input class="btn btn-primary" type="submit" value="ค้นหา">
</form>
<hr>
<ul class="list-group">
{% if object_list %}
  {% for game in object_list %}
    <li class="list-group-item">
      <h2>{{game}} <a class="btn btn-light" href="{% url 'game' pk=game.pk %}">ดูเพิ่มเติม</a></h2>
      <ul class="list-group">
      {% for product in game.products.all  %}
          <li class="list-group-item">
            {% if product.seller.facebook %}
              {% if product.seller.facebook_link %}
                <h4>ติดต่อ Facebook : <a href={{product.seller.facebook_link}}>{{product.seller.facebook}}</a> <a class="btn btn-primary" href="{% url 'accounts:profile' pk=product.seller.pk %}">โปรไฟล์ผู้ขาย</a></h4>
              {% else %}
                <h4>ติดต่อ Facebook : {{product.seller.facebook}}<a class="btn btn-primary" href="{% url 'accounts:profile' pk=product.seller.pk %}">โปรไฟล์ผู้ขาย</a></h4>
              {% endif %}
            {% else %}
              <h4>ติดต่อผู้ขาย : {{product.seller}}</h4> **ผู้ใช้ยังไม่ได้ตั้งค่า Facebook โปรดระวัง**
            {% endif %}
            <h4>ราคา : {{product.price}}</h4>
          </li>
      {% endfor %}
      </ul>
    </li>
  {% endfor %}
{% else %}
    <h1>ไม่พบการค้นหา</h1>
{% endif %}


</ul>
{% endblock %}

templates/game/productcreate.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
  <h1>ลงขายเกม</h1>
  <form method="post">
      {% csrf_token %}
      เกม : {{ form.game }}<p></p>
      ราคา : {{ form.price }}<p></p>
    <input type="submit" value="submit" class="btn btn-sm btn-primary"><p></p>
    <a class="btn btn-warning" href="{% url 'gamerequest' %}">ไม่มีเกมที่คุณต้องการขาย?</a>
  </form>
</div>

{% endblock %}

templates/game/productdelete.html
{% extends 'base.html' %}
{% block content %}
<h2>คุณกำลังจะลบ {{product.game}} ?</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-danger" value="ลบ">
  <a href="{% url 'game:product' pk=product.pk %}">ยกเลิก</a>
</form>
{% endblock %}

templates/game/productdetail.html
{% extends 'base.html' %}
{% block content %}
  <div class="jumbotron">
    <a href="{% url 'game' pk=product_detail.game.pk %}">
    <h1>เกม : {{product_detail.game}}</h1></a>
    <h2>ราคา : {{product_detail.price}}</h2>
    <h2>ผู้ขาย : {{product_detail.seller}}</h2>
    {% if user == product_detail.seller.user %}
      <a class="btn btn-warning" role="button" href="{% url 'game:product_edit' pk=product_detail.pk %}">แก้ไข</a>
      <a class="btn btn-danger" role="button" href="{% url 'game:product_delete' pk=product_detail.pk %}">ลบ</a>
    {% endif %}
  </div>
{% endblock %}

templates/game/productedit.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="submit">
</form>
{% endblock %}

templates/game/productlist.html
{% extends 'base.html' %}
{% block content %}
<h1>{{game.name}}</h1>

{% if game.products.all %}
  <h2>สินค้าที่มี : </h2>
  <ul class="list-group">
  {% for product in game.products.all %}
    <li class="list-group-item">
      <h2>ราคา : {{product.price}}</h2>
      <h2>ผู้ขาย : <a href="{% url 'accounts:profile' pk=product.seller.pk %}">{{product.seller}}</h2></a>
    </li>
  {% endfor %}
  </ul>
{% else %}
  <h2>ยังไม่มีคนลงขายเกม</h2>
{% endif %}


{% endblock %}

templates/gamerequest.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
  <h1>เสนอเกม</h1>
  <form class="form-group" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class='btn btn-primary' value="ส่งคำขอ">
  </form>
</div>


{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
  <h1>หน้าหลัก</h1>
  <a class="btn btn-primary" href="{% url 'accounts:register' %}">สมัครสมาชิก</a>
  <a class="btn btn-primary"  href="{% url 'gamelist' %}">หน้าร้านค้า</a>
  {% if user.is_authenticated %}
      <a class="btn btn-primary"  href="{% url 'accounts:profile_edit' pk=user.profile.pk %}">แก้ไขข้อมูลสมาชิก</a>
      <a class="btn btn-primary"  href="{% url 'accounts:profile' pk=user.profile.pk %}">หน้าสมาชิก</a>
  {% endif %}
  <p></p>
  {% if news %}
    <h3>กระดานข่าว</h3>
    <ul class="list-group">
    {% for new in news %}
      <li class="list-group-item">
        <p>{{new.text}}</p>
        {{new.time}}
      </li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
<div class="row">
  <div class="w-50 p-3">
  {% if games %}
    <h3>เกมแนะนำ</h3>
    <ul class="list-group">
    {% for game in games %}
      <li class="list-group-item">
        <a href="{% url 'game' pk=game.pk %}">{{ game.name }}</a>
      </li>
    {% endfor %}
    </ul>
  {% endif %}
  </div>
  <div class="w-50 p-3">
    {% if profiles %}
      <h3>ผู้ใช้</h3>
      <ul class="list-group">
      {% for profile in profiles %}
        <li class="list-group-item">
          <a href="{% url 'accounts:profile' pk=profile.pk %}">{{ profile.user }}</a>
        </li>
      {% endfor %}
      </ul>
    {% endif %}
  </div>
</div>


{% endblock %}